language: python
cache: pip
sudo: false

  
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

env:
  global:
    - TEST_DEPS="pytest pytest-cov"
    - TEST_DIR=/tmp/_schemaperfect/


before_install:
  - pip install pip --upgrade;
  - pip install $TEST_DEPS;

install:
  - pip install -e .;

script:
  - mkdir -p $TEST_DIR;
  - cd $TEST_DIR && python -m pytest --pyargs --doctest-modules schemaperfect --cov-report term-missing --cov=schemaperfect;
